version: "3.9"

services:
  langgraph-app:
    build: .
    container_name: langgraph-app
    stdin_open: true
    tty: true
    environment:
      - OPENAI_API_KEY={OPENAI_API_KEY}
    volumes:
      - .:/app
